Add customer specs
nebulab/solidus_square pull request #14
Opened 2021-10-05 18:20 UTC by mcrisologo

2021-10-05 18:23 UTC, mcrisologo commented
Note: 
Fetching initial recording is a bit problematic. 
Seems like pinging to the sandbox API is intermittent (even on console).
Using stubs instead.

2021-10-19 09:55 UTC, DanielePalombo requested changes
There are some requested changes.

2021-10-19 09:55 UTC, DanielePalombo commented on spec/support/vcr.rb
> +  config.allow_http_connections_when_no_cassette = false
[This part](https://github.com/solidusio-contrib/solidus_paypal_marketplace/blob/main/spec/support/vcr.rb#L58-L59) would be useful to invalidate the cassettes.

2021-10-19 09:55 UTC, DanielePalombo commented on spec/fixtures/vcr_cassettes/customers/create/valid.yml
> +          - Bearer EAAAEJ2wQT1qUQIvMGlImkhphBakgTk-r8rhyznGQ_5IvSKFpKk4vmMexZRGAIgR
Please filter out the sensitive data with this [code](https://github.com/solidusio-contrib/solidus_paypal_marketplace/blob/main/spec/support/vcr.rb#L15-L17)

2021-10-19 09:55 UTC, DanielePalombo commented on spec/services/solidus_square/customers/create_spec.rb
> +      allow_any_instance_of(described_class).to receive(:search_customer).and_return({ 'id' => 111 })
Do you mind replacing these `allow_any_instance_of``s in favor of Double and specific allow?

2021-10-19 09:55 UTC, DanielePalombo commented on spec/support/solidus.rb
> +#require 'spree/testing_support/order_walkthrough'
This file can be removed

2021-10-19 09:55 UTC, DanielePalombo commented on app/models/solidus_square/gateway.rb
> +    def create_customer(user, address)
missing test

2021-10-19 12:46 UTC, DanielePalombo commented on app/models/solidus_square/payment_method.rb
> +  class PaymentMethod < SolidusSupport.payment_method_parent_class
This is also related to #7

2021-10-20 10:46 UTC, merged